AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-slack-slash-command

  Sample SAM Template for sam-slack-slash-command

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  FrontFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: front/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /slack-slash-command
            Method: post
  BackFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: back/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FrontApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/slack-slash-command/"
  FrontFunction:
    Description: "FrontFunction ARN"
    Value: !GetAtt FrontFunction.Arn
  FrontFunctionIamRole:
    Description: "Implicit IAM Role created for FrontFunction"
    Value: !GetAtt FrontFunctionRole.Arn

  BackFunction:
    Description: "BackFunction ARN"
    Value: !GetAtt BackFunction.Arn
  BackFunctionIamRole:
    Description: "Implicit IAM Role created for BackFunction"
    Value: !GetAtt BackFunctionRole.Arn
